logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    com.dxc.eproc.bidding: DEBUG

server:
  port: 9191
  
spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true
  
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/master_management?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: welcome
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  transaction:
    default-timeout: 120    
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.enable_lazy_load_no_trans: true
      hibernate.connection.provider_disables_autocommit: true
 
hibernate:
  dialect: org.hibernate.dialect.MySQL8Dialect
  connection:
    url: jdbc:mysql://localhost:3306/master_management
    driverclass: com.mysql.jdbc.Driver
    username: root
    password: welcome
  showsql: false
  formatsql: false
  jdbc:
    batchsize: 1000
  orderinserts: false
  orderupdates: false
hbm2ddl:
  auto: none
  
opentracing:
  jaeger:
    expand-exception-logs: true
    #udp-sender:
      #host: 130.175.175.137
      #port: 6831
    http-sender:
      url: http://localhost:5778/api/traces  
    enabled: false
    enable-b3-propagation: true
    log-spans: true
    const-sampler:
      decision: true
     
 
          